"""

Revision ID: 334c6752a8f7
Revises: 9adb4e4757d3
Create Date: 2025-05-11 20:37:08.147617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334c6752a8f7'
down_revision: Union[str, None] = '9adb4e4757d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('emails_folder_id_fkey', 'emails', type_='foreignkey')
    op.create_foreign_key(None, 'emails', 'folders', ['folder_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('folders_account_id_fkey', 'folders', type_='foreignkey')
    op.create_foreign_key(None, 'folders', 'mail_accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('mail_accounts_user_id_fkey', 'mail_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'mail_accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mail_accounts', type_='foreignkey')
    op.create_foreign_key('mail_accounts_user_id_fkey', 'mail_accounts', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.create_foreign_key('folders_account_id_fkey', 'folders', 'mail_accounts', ['account_id'], ['id'])
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.create_foreign_key('emails_folder_id_fkey', 'emails', 'folders', ['folder_id'], ['id'])
    # ### end Alembic commands ###
