"""

Revision ID: 9adb4e4757d3
Revises: d3cf08d78931
Create Date: 2025-05-11 19:52:51.210140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9adb4e4757d3'
down_revision: Union[str, None] = 'd3cf08d78931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['mail_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('emails', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'emails', 'folders', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_column('emails', 'folder_id')
    op.drop_table('folders')
    # ### end Alembic commands ###
